### ISSUE TITLE
gn_search command UnicodeEncodeError on windows

### ISSUE THREAD

**Issue by miranda-zhang** [dsoprea/GeonamesRdf#4]
```
$ gn_search dsoprea -p query "Middle East and Africa" -p max_rows 10
[http://sws.geonames.org/359796/]: [Suez]
[http://sws.geonames.org/359797/]: [Suez]
[http://sws.geonames.org/7521348/]: [Ain Sukhna]
[http://sws.geonames.org/360542/]: [Al Qurayn]
Traceback (most recent call last):
  File "C:/Users/admin-u5214628/.virtualenvs/geonames_rdf/Scripts/gn_search", line 81, in <module>
    _main()
  File "C:/Users/admin-u5214628/.virtualenvs/geonames_rdf/Scripts/gn_search", line 74, in _main
    format(id_, name))
  File "C:\users\admin-u5214628\.virtualenvs\geonames_rdf\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0163' in position 40: character maps to <undefined>
(geonames_rdf)

```
Testing git bash terminal
```
$ printf '\u0163\n'
ţ
```

**Comment by miranda-zhang** [comment]
`export PYTHONIOENCODING=UTF-8`
Solved my problem
